name: Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc ccache

      - name: Install Repo
        run: |
          mkdir ~/bin
          curl storage.googleapis.com > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Sync Manifest
        run: |
          mkdir workspace
          cd workspace
          repo init --depth=1 -u github.com -b twrp-11
          repo sync -j$(nproc --all) --force-sync

      - name: Clone Device Tree
        run: |
          cd workspace
          git clone github.com ./device/lenovo/YT-X705X

      - name: Build TWRP
        run: |
          cd workspace
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          # Changed from twrp_ to omni_ to match your repo's makefile
          lunch omni_YT-X705X-eng
          make recoveryimage -j$(nproc --all)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-YT-X705X
          path: workspace/out/target/product/YT-X705X/recovery.img
