name: Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc ccache

      - name: Install Repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Sync Manifest
        run: |
          mkdir workspace
          cd workspace
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-11
          repo sync -j$(nproc --all) --force-sync

     - name: Clone Device Tree
        run: |
          cd workspace
          # FIXED: Path must match your BoardConfig.mk DEVICE_PATH
          git clone https://github.com/robloxguyscripts-jpg/android_device_lenovo_YT-X705X device/lenovo/android_device_lenovo_YT-X705X

      - name: Build TWRP
        run: |
          cd workspace
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch omni_YT_X705X-eng
          mka recoveryimage -j$(nproc --all)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-YT_X705X-Result
          path: workspace/out/target/product/YT_X705X/recovery.img
      - name: Build TWRP
        run: |
          cd workspace
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch omni_YT_X705X-eng
          mka recoveryimage -j$(nproc --all)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-YT_X705X-Result
          path: workspace/out/target/product/YT_X705X/recovery.img
